CREATE TABLE COMPANIES
(
	Id INT IDENTITY,
	CNPJ VARCHAR(14) NOT NULL,
	FantasyName VARCHAR(255) NOT NULL,
	SocialName VARCHAR(255) NOT NULL,
	CONSTRAINT COMPANIES_PK PRIMARY KEY(ID)
);

CREATE TABLE ADRESSES
(
	Id INT IDENTITY,
	Street VARCHAR(255),
	Number INT, 
	Complement VARCHAR(255),
	City VARCHAR(200),
	StateName VARCHAR(200),
	UF VARCHAR(2),
	CompanyId INT NOT NULL,
	CONSTRAINT ADRESSES_COMPANIES_FK FOREIGN KEY (CompanyId) REFERENCES COMPANIES(Id),	
	CONSTRAINT ADRESSES_PK PRIMARY KEY(ID)
);

CREATE TABLE DEPARTMENTS
(
	Id INT IDENTITY,
	CompanyId INT NOT NULL,
	CONSTRAINT DEPARTMENTS_COMPANIES_FK FOREIGN KEY (CompanyId) REFERENCES COMPANIES(Id),
	CONSTRAINT DEPARTMENTS_PK PRIMARY KEY(ID)
);

CREATE TABLE COLLABORATORS
(
	Id INT IDENTITY,
	Name VARCHAR(255) NOT NULL,
	DepartmentId INT NOT NULL,
	CollaboratorId INT,
	CompanyId INT NOT NULL,
	CONSTRAINT COLLABORATORS_COMPANIES_FK FOREIGN KEY (CompanyId) REFERENCES COMPANIES(Id),
	CONSTRAINT COLLABORATORS_DEPARTMENTS_FK FOREIGN KEY (DepartmentId) REFERENCES DEPARTMENTS(Id),
	CONSTRAINT COLLABORATORS_PK PRIMARY KEY(ID),
	CONSTRAINT COLLABORATORS_COLLABORATORS_FK FOREIGN KEY (CollaboratorId) REFERENCES COLLABORATORS(Id),
);

CREATE TABLE COLLABORATORS_SERVICES
(
	Id INT IDENTITY,
	Name VARCHAR(150) NOT NULL,
	CompanyId INT NOT NULL,
	CONSTRAINT COLLABORATORS_SERVICES_COMPANIES_FK FOREIGN KEY (CompanyId) REFERENCES COMPANIES(Id),
	CONSTRAINT COLLABORATORS_SERVICES_PK PRIMARY KEY(ID),
	CONSTRAINT COLLABORATORS_SERVICES_COMPANIES_FK FOREIGN KEY (CompanyId) REFERENCES COMPANIES(Id)
);

CREATE TABLE COLLABORATORS_SERVICES_TYPE
(
	Id INT IDENTITY,
	Nome VARCHAR(150) NOT NULL,
	CollaboratorsServicesId INT NOT NULL,
	CompanyId INT NOT NULL,
	CONSTRAINT COLLABORATORS_SERVICES_TYPE_COMPANIES_FK FOREIGN KEY (CompanyId) REFERENCES COMPANIES(Id),
	CONSTRAINT COLLABORATORS_SERVICES_TYPE_PK PRIMARY KEY(ID),
	CONSTRAINT COLLABORATORS_SERVICES_TYPE_COLLABORATORS_SERVICES_FK FOREIGN KEY (CollaboratorsServicesId) REFERENCES COLLABORATORS_SERVICES(Id)
);

